version: '3.8'

services:
  backend:
    image: oksesaneka22/projk:backend1.2
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    image: oksesaneka22/projk:frontend1.2
    ports:
      - "80:80"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
